### PR TITLE
Fix configure ac for autoconf 2.70

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by simo5** [comment]
This should fix #643

**Comment by simo5** [comment]
FWIW: Tested locally and it does fix #643, I included these patches in the Fedora Rawhide package.

**Comment by Biswa96** [comment]
Any progress on this PR to be merged?

**Comment by quanah** [comment]
Needs me to finish getting the CLA bot set up and for the author to sign the CLA, for starters.

**Comment by praiskup** [comment]
Feel free to use patches under Public Domain, if that helps.

**Comment by simo5** [comment]
FWIW, authors do not have a lot of interest in signing CLAs for half-dead projects, I *strongly* suggest you use an inbound-outbound license instead, and a DCO, to lower barriers to contribution.
Suggested reading: https://opensource.com/article/19/2/cla-problems

**Comment by quanah** [comment]
Please update your pull request so it has been signed off on in accordance with our DCO.  Thanks!

**Comment by praiskup** [comment]
Done, ptal.

**Pull request merged**
