### PR TITLE
digestmd5: Drop the mechanism

### PR DESCRIPTION
**Pull request by bgermann**
The DIGEST-MD5 mechanism has been marked as historic by RFC 6331 for a decade. Drop it from cyrus-sasl.

### CODE REVIEW

**Comment by Neustradamus** [comment]
To follow, thanks @bgermann!

**Comment by quanah** [comment]
@hyc should be ready for review!

**Comment by quanah** [comment]
@bgermann looks like the inclusion of the new opaque module means the PR needs an update again.

**Comment by bgermann** [comment]
Done.

**Comment by hyc** [comment]
Sorry, I pushed a couple tweaks to master because it wasn't compiling, which created a trivial conflict with plugins/digestmd5.c. Please resolve that, thanks. Otherwise, it all builds fine.

**Pull request merged**
