### PR TITLE
Some basic PLAIN auth tests

### PR DESCRIPTION
**Pull request by beldmit**
Here are some very basic PLAIN sasl mechanism tests.

It's worth renaming the t_gssapi* files to something more general, if there is any interest to this PR.

### CODE REVIEW

**Comment by simo5** [comment]
Looks good to me.

**Comment by quanah** [comment]
Please update your pull request so it has been signed off on in accordance with our DCO.  Thanks!

**Comment by beldmit** [comment]
@quanah could you please provide a more exact link?
Sorry for the delay with response

**Comment by beldmit** [comment]
@quanah Done

**Review by hyc — APPROVED** [review]

**Pull request merged**
