### PR TITLE
opaque mechanism from https://github.com/stef/libopaque/tree/master/sasl

### PR DESCRIPTION
**Pull request by stef**
this PR upstreams the OPAQUE mechanism implemented as an out-of-tree module in https://github.com/stef/libopaque/.

the mechanism in `plugins/opaque.c` is licensed by default LGPL (as the rest of libopaque), but i'm open to relicense to MIT/BSD style licensing for cyrus-sasl, using the default cmu license did not seem appropriate here.

the included HKDF implementation comes straight from: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_kdf/hkdf/kdf_hkdf_sha512.c and is licensed just as libsodium under the ISC license. This is needed, as there has been no official libsodium release which contains this HKDF implementation. If there ever is a new libsodium release this internal copy will not be used, as per the configure.am.

furthermore this implementation comes with a verbatim copy of opaque.c from libopaque, which makes it easier to package cyrus for various distributions that have not packaged libopaque yet. the appropriate configure.am parts should make sure, if there is a system-wide libopaque is installed that will be used instead of the internal copy. this internal copy is LGPL licensed, should be compatible with the rest of cyrus-sasl and also not affect the license of anything besides the opaque mechanism.

### CODE REVIEW

**Comment by hyc** [comment]
I think using a compatible license like LGPL should be fine. I'll note that my plugins/ldapdb.c is licensed under the OpenLDAP public license and there was never any issue accepting that code.

**Review by hyc — APPROVED** [review]
A couple minor merge conflicts need resolving now, but otherwise OK.

**Comment by quanah** [comment]
@stef Looks like a great addition for cyrus-sasl 2.2 release.  Once you update the PR to address the conflicts we'll get it merged in

**Comment by quanah** [comment]
It would also be good to update the docs found in the docsrc/ directory with this as well, but that can be a separate commit.

**Comment by stef** [comment]
i resolved the conflicts.

**Comment by quanah** [comment]
@stef it says that conflicts still exist (but not what they are).. not sure what the issue is.

**Comment by stef** [comment]
it says here: 

> This branch has no conflicts with the base branch

**Comment by quanah** [comment]
> it says here:
> 
> > This branch has no conflicts with the base branch

'This branch cannot be rebased due to conflicts'

**Comment by quanah** [comment]
cant-merge-756

**Comment by quanah** [comment]
I downloaded your PR as a patch, and it clearly has conflicts.  I suspect your base 'master' is out of date:

```
git am 756.patch
Applying: opaque mechanism from https://github.com/stef/libopaque/tree/master/sasl
.git/rebase-apply/patch:1320: trailing whitespace.

error: patch failed: plugins/Makefile.am:63
error: plugins/Makefile.am: patch does not apply
error: patch failed: plugins/makeinit.sh:1
error: plugins/makeinit.sh: patch does not apply
Patch failed at 0001 opaque mechanism from https://github.com/stef/libopaque/tree/master/sasl
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

**Comment by quanah** [comment]
What you're working from is clearly out of date as your PR still references KERBEROSv4 bits that do not exist in the current master branch.

**Comment by quanah** [comment]
also NTLM which does not exist in current master.  Possibly other issues.

**Comment by stef** [comment]
something is weird.

**Comment by stef** [comment]
> What you're working from is clearly out of date as your PR still references KERBEROSv4 bits that do not exist in the current master branch.

can you quote where the patch references krbv4 please?

**Comment by quanah** [comment]
```
wget https://patch-diff.githubusercontent.com/raw/cyrusimap/cyrus-sasl/pull/756.patch
grep -i kerb 756.patch
 EXTRA_LTLIBRARIES = libplain.la libanonymous.la libkerberos4.la libcrammd5.la \
-kerberos4_init.c login_init.c plain_init.c srp_init.c otp_init.c ntlm_init.c \
+kerberos4_init.c login_init.c plain_init.c srp_init.c opaque_init.c otp_init.c ntlm_init.c \
-for mech in anonymous crammd5 digestmd5 scram gssapiv2 kerberos4 login ntlm otp passdss plain srp gs2; do
+for mech in anonymous crammd5 digestmd5 scram gssapiv2 kerberos4 login ntlm otp passdss plain srp opaque gs2; do
```

**Comment by stef** [comment]
it's not here: https://github.com/cyrusimap/cyrus-sasl/pull/756/files#diff-3f9546c714917fd204c5dfe4cefc81833518a95f2dad4969bff2a4301297182b and the other quoted occurrence is also missing. what is going on?

**Comment by stef** [comment]
it seems you see the version before the conflict resolution, and i see the version after. why we see two different versions is the solution to this thread.

**Comment by stef** [comment]
huh, when i do 
```
curl -L https://github.com/cyrusimap/cyrus-sasl/pull/756.patch | fgrep kerb
```
i get the same result as you. while here on the web UI of github i see what i resolved earlier.

**Comment by stef** [comment]
https://github.com/cyrusimap/cyrus-sasl/pull/756/commits/ab9fe190fc29d33fe903ad4e25f52df7a9f55d92

why this is missing?

**Comment by stef** [comment]
the conflict resolution is also listed on this page: https://github.com/cyrusimap/cyrus-sasl/pull/756/commits

**Comment by quanah** [comment]
Because it's a merge of a branch, rather than a commit on top of a current version of master.

**Comment by stef** [comment]
> Because it's a merge of a branch, rather than a commit on top of a current version of master.

ok? and what shall i do now to make you see the same state as me?

**Comment by stef** [comment]
i hope this force-push solves the mystery.

**Comment by quanah** [comment]
No, you are still merging master into your branch after your commits.

You need to remove your commits, then REBASE (not merge) your branch with current master, and then apply your commits on top and force push.

**Comment by stef** [comment]
i'm inclined to just close this PR and move on...

**Comment by quanah** [comment]
Well it's definitely important to learn how to use git correctly.  However if you want to close this PR and open a new one with your changes based on top of current master that would work as well.

**Comment by stef** [comment]
i don't see how this is wrong, everything is green here.

**Comment by stef** [comment]
and this discussion drains my energy

**Comment by quanah** [comment]
> and this discussion drains my energy

You are making your changes and then merging master on top, which isn't the correct git workflow.  You need to do what I noted in https://github.com/cyrusimap/cyrus-sasl/pull/756#issuecomment-1645684789 for the PR to be useable.  It appears you're running 'git merge master' at some point which is not a valid step to take.  It seems the fact that github shows it as green to you is a bug in github's UI.

**Comment by stef** [comment]
i find this comment:

> Well it's definitely important to learn how to use git correctly.

passive aggressive and insulting.

**Comment by quanah** [comment]
> i find this comment:
> 
> > Well it's definitely important to learn how to use git correctly.
> 
> passive aggressive and insulting.

It wasn't meant that way at all.  If you will be working with PRs and git, however, understanding how to correct issues like this is important knowledge to have.

**Comment by stef** [comment]
i'm taking a timeout. good luck.

**Comment by quanah** [comment]
@stef We very much want your commit, but I can't do anything about the fact that github will not accept it in the way in which the current PR exists.  I don't know how you've set up your fork, but in my case it the steps would be something along the lines of:
1. git checkout <your working branch for this PR>
2. git format-patch -1 <commit hash> for each of the changes to save them out to a patch file
2. git reset --hard HEAD^1 (back out one commit, repeat until back to original state prior to making your changes) 
3. Ensure a remote is configured for the upstream repo (this one), such as: git remote add upstream https://github.com/cyrusimap/cyrus-sasl.git
4. git fetch upstream
5. git pull --rebase upstream master (rebase upstream master on this branch)
6. git am <patches>, correcting as needed
7. git push -f

That's off the top of my head, but I think generally correct.

**Comment by quanah** [comment]
I manually merged the PR.  But hopefully the last comment helps you in the future if you encounter such an issue. :)

**Comment by stef** [comment]
thx

**Pull request merged**
