### PR TITLE
Added Visual Studio solution

### PR DESCRIPTION
**Pull request by Ri0n**
Just two projects added at the moment:
sasl lib itself and its "common" dependency.

Updated code to compile with UNICODE define.
Fixed some warnings.

I'll update this pull request as soon as I have more subprojects added.

### CODE REVIEW

**Comment by Ri0n** [comment]
Added lmdb support.
Started adding plugins.

**Comment by Ri0n** [comment]
Added sasldb plugin compiles as dll. other plugins are static.

**Comment by sfhacker** [comment]
image

**Comment by sfhacker** [comment]
We do not know how to test this distribution! Are there any tests we can run? Are there any examples?

image

**Comment by Ri0n** [comment]
regarding runtime tests, I tested it with [QCA](https://github.com/KDE/qca) + [Psi](https://github.com/psi-im/)
I guess it's a lot of work for you to compile all of these.

I think you it's possible to use some stuff from cyrus-sasl/example dir but I never tried to compile it. And I don't see unit tests. Basically I don't know how cyrus-sasl devs tested it previously but probably it's fine to continue testing the same way.

**Comment by Ri0n** [comment]
Hm I'll try to make a conan config file and check if OpenSSL stuff can automated.

**Comment by Ri0n** [comment]
good news: visual studio instruction from conan project works.
not that good: It's necessary to figure out how to generate automatically conan's property sheet per selected configuration.

I'll try to play with this tomorrow morning. but for now there is some work in progress I've uploaded here https://pastebin.com/6pKPDvwP

**Comment by nacho** [comment]
This is cool stuff, although just wanted to point out that would be also awesome to try to build the project using meson, what this would give us?
 - maintaining visual studio projects is a pain, if you want to build with 2017 or 2013 you need to make the conversion and be sure it works properly and keep them in sync
 - we could have the same build system for linux and windows
 - it is faster
 - easier to maintain

This is just a side note, I am not opposing to getting this in in the meantime.

**Comment by Ri0n** [comment]
I agree about meson. I thought about it but for some reason decided keep working on native Visual Studio solution. 
The same for cmake. It can generate Visual Studio solutions/projects and build for everything for any OS from command line.

**Comment by Ri0n** [comment]
I've switched OpenSSL to use conan and updated readme. One thing I don't like - it's required to restart Visual Studio after generation of property sheets by "configure" target.
So now one should not care about OpenSSL. The solution will download and install it automatically.

**Comment by Ri0n** [comment]
I'll try to add lmdb to conan repos too and add some deploy stuff for distribution purposes.

**Comment by nacho** [comment]
If you need to build lmdb with visual studio have a look at https://github.com/wingtk/gvsbuild

**Comment by Ri0n** [comment]
Thanks @nacho. I didn't know about gvsbuild, so I quickly crafted my own lmdb solution https://github.com/Ri0n/lmdb
I'll use gvsbuild if it suits well for conan.

**Comment by ksmurchison** [comment]
@aamelnikov  Can you review this?  I don't have a Windows dev environment

**Comment by Ri0n** [comment]
by the way I'm now trying to rewrite to be fully driven by Conan package manager. So it will be impossible to build directly with Visual Studio but Conan will prepare Visual Studio environment, build and upload artifacts to bintray repository just with two commands.
The same for applications using cyrus-sasl on Windows. It will be just one command to download cyrus-sasl and all its dependencies and setup the application's project to use the deps.

Builds will be controlled by AppVeyor cloud service and it will report build results. So manual interactions are not needed.
I'm little stuck with krb5 dep now since nmake is not directly supported by Conan atm but I'm on the way to resolve it. Then it will be not that hard to add Mac OS builds via Conan too.

Eventually it will be very handy to build and use.

**Comment by sfhacker** [comment]
@Ri0n Is this 'enhancement' ready to be tested using VS? Last time I tried I came across several (compilation & linking) issues. See screenshots above.
Can you also include the tests and examples in the VS solution?

Cheers.

**Comment by Ri0n** [comment]
@sfhacker 
regarding currently committed version and its compilation, README.md in win32 folder should explain everything. Just open https://github.com/Ri0n/cyrus-sasl/tree/master/win32 and scroll down.
test and examples.. hm. tell me what sources have to be compiled and I'll try to add them.  I see here some **sample** directory. I can try to add it to VS project.

**Comment by Ri0n** [comment]
@sfhacker to avoid messing with all the deps, you will have to disable sasldb plugin and gssapi plugin via visual studio configuration manager

**Comment by sfhacker** [comment]
Ciao.
Is this PR being reviewed and tested?
We did a quick review the other day and there are some questions, points to discuss, and so on.
Thanks for this contribution, though.

- Dependencies

    >>> conan package manager (https://conan.io/ It's needed to install OpenSSL libraries and other deps)

        	Notes: - Not sure how many people use conan, but we don't!
                	       - OpenSSL is already installed on our system.  (Windows)

	>>> LMDB (One can try forked version https://github.com/Ri0n/lmdb till original master is fixed for Visual Studio. . But you can just disable sasldb subproject.)

                 Notes: - LMDB is already installed on our system. Which fix are you talking about?
	
	>>> MIT Kerberos for Windows (http://web.mit.edu/kerberos/dist/index.html select full install. required only for gssapiv2 plugin which may be disabled if not needed)
	
	Notes: - Again, not sure how many people use this implementation. We use Heimdal Kerberos and it       is already installed and set up (and running) on our system. (Windows)

- VS Solution

    Notes: - There are no sign of tests.
	       - There are no sign of examples.

- Testing

    Questions: - Either before or after its installation, how can the main library and all the plugins
        	             be tested? Please, advise a set of steps.
                     The Windows binary distribution we use contains plenty of tests we can run after  
                     downloading it.

**Comment by Ri0n** [comment]
John, probably if you review Conan you would like it. Basically it allows to automate a lot of devops stuff. So you are going to have:

1. The latest stable and secure version of OpenSSL as well as any other dependency (of course if security is somewhat important for you).
2. Support for multiple toolchains out of the box.
3. Automatic artifactory and easy deploy of your software.

---

lmdb from master currently doesn't build. It was broken by a commit removing ntdll dependency. I've fixed it in my fork.

---

About kerberos impl I have no idea. I just needed a working plugin. I'll review Heimdal too but it already goes far away from my original needs.

---

Probably I won't provide tests and examples. Basically I already did some tests with my application and it works. Even so I'll check if it's possible to add to build some cyrus-sasl internal example code.

Most likely I'll change quite a bit plugins loading code to be more flexible. Some instructions will be added after that.

**Comment by Ri0n** [comment]
John, you know, you are right. While Conan is cool enough it's not a reason to break a regular workflow that much. It's better to have generic standalone VS project and Conan as an independent addon.

**Comment by stringarray** [comment]
Thanks for making Conan optional.

**Comment by nacho** [comment]
@Ri0n fwiw I ported lmdb to meson. You can find it here: https://github.com/wingtk/lmdb/tree/wip/meson

**Comment by Ri0n** [comment]
@nacho, great! 

I temporarily stopped working on cyrus-sasl Windows project improvements. Conan lacks some very heavy but still required dependencies for my application and it hinders me to keep working on Windows at all while Linux already has everything required.

**Comment by sfhacker** [comment]
We are planning on releasing Cyrus SASL for Windows soon and we were wondering if there would be a new release (2.1.28 ?) soon? @ksmurchison 
We have downloaded and built master branch and so far so good. We have run several tests and it looks good.

**Output of pluginviewer**
...
...
SRP PASSDSS-3DES-1 SCRAM-SHA-256 SCRAM-SHA-1 GSS-SPNEGO GSSAPI DIGEST-MD5 EXTERNAL OTP CRAM-MD5 NTLM LOGIN PLAIN ANONYMOUS
...
...

**Output of sample-server against GSSAPI**
...
...
Negotiation complete
Username: ken
Realm: (NULL)
SSF: 112
sending encrypted message 'srv message 1'
S: AAAASgUEB/8AAAAcAAAAAASFxxtXtSGpg3oQIotgBUewBSZkntmV8zfzNLFEPxmw+t7Bbv80/fJHW62WAdTwqWNHrWmNdLR0NWzp1AhY
Waiting for encrypted message...
C: AAAATQUEBv8AAAAcAAAAACWqv/xEnMuMu1a6USfEDv9VUA+ol6WNmSMeWkZz4K05rXpYBzMUnONgdzq6Lvn3MXtjKiw+JxItkoRsYMAQ87UB
got ''
received decoded message 'client message 1'

We are now about to integrate SASL with OpenLDAP and run more tests.

Thanks.

**Comment by ksmurchison** [comment]
@aamelnikov  Can you sanity check this PR?

**Comment by sfhacker** [comment]
**Integration with OpenLDAP 2.4.46**

openldap-sasl

How is the new release progressing?

**Comment by ksmurchison** [comment]
@Ri0n: See issue #538.  Unless you can fix this, I will have to revert this PR.

**Comment by Ri0n** [comment]
I'll take a look when got home

**Comment by ksmurchison** [comment]
I have no windows build environment so in lieu of any other reviews I trusted the PR. If not resolved by tomorrow, I will probably revert that commit

**Comment by Ri0n** [comment]
I'll review this in a few hours. Had no spare time for that so far. 
But I'm fine with reverting anyway. So go ahead if it's a showstopper for you.
I believe the fix is quite trivial if it ever required with recent mingw (VS is no affected)

**Comment by Ri0n** [comment]
Ok, the problem is in filename case. In mingw it's lower-case (not camel). I updated the issue.
In any case I didn't try to compile with mingw and it will take some time to prepare the environment.

**Pull request merged**
